<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="C:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\bin\Debug\Caesura.dll" total="15" errors="3" failures="2" not-run="0" inconclusive="0" ignored="0" skipped="0" invalid="0" date="2013-03-22" time="02:34:39">
  <environment nunit-version="2.6.2.12296" clr-version="2.0.50727.5466" os-version="Microsoft Windows NT 6.1.7601 Service Pack 1" platform="Win32NT" cwd="C:\Program Files (x86)\NUnit 2.6.2\bin" machine-name="CARTERJ3TOWER" user="Carterj3-Tower" user-domain="Carterj3Tower" />
  <culture-info current-culture="en-US" current-uiculture="en-US" />
  <test-suite type="Assembly" name="C:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\bin\Debug\Caesura.dll" executed="True" result="Failure" success="False" time="0.128" asserts="0">
    <results>
      <test-suite type="Namespace" name="Caesura" executed="True" result="Failure" success="False" time="0.127" asserts="0">
        <results>
          <test-suite type="TestFixture" name="aSocketTest" executed="True" result="Failure" success="False" time="0.060" asserts="0">
            <results>
              <test-case name="Caesura.aSocketTest.testaSocketConnectHostLengthZero" executed="True" result="Success" success="True" time="0.001" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketConnectNullHost" executed="True" result="Success" success="True" time="0.000" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketConstructor" executed="True" result="Success" success="True" time="0.000" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketConstructorGivenAnSocket" executed="True" result="Success" success="True" time="0.000" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketListen" executed="True" result="Error" success="False" time="0.001" asserts="0">
                <failure>
                  <message><![CDATA[System.InvalidOperationException : You must call the Bind method before performing this operation.]]></message>
                  <stack-trace><![CDATA[at System.Net.Sockets.Socket.Accept()
at Caesura.aSocketTest.<testaSocketListen>b__0(Socket a) in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\aSocketTest.cs:line 72
at Rhino.Mocks.RhinoMocksExtensions.Expect[T,R](T mock, Function`2 action)
at Rhino.Mocks.RhinoMocksExtensions.Stub[T,R](T mock, Function`2 action)
at Caesura.aSocketTest.testaSocketListen() in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\aSocketTest.cs:line 72
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="Caesura.aSocketTest.testaSocketRecieveLengthLongerThanBuffer" executed="True" result="Success" success="True" time="0.000" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketRecieveNegativeLengthBuffer" executed="True" result="Success" success="True" time="0.000" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketRecieveNullBuffer" executed="True" result="Success" success="True" time="0.000" asserts="1" />
              <test-case name="Caesura.aSocketTest.testaSocketRecieveObjectDisposedException" executed="True" result="Error" success="False" time="0.001" asserts="0">
                <failure>
                  <message><![CDATA[System.Net.Sockets.SocketException : A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied]]></message>
                  <stack-trace><![CDATA[at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 size, SocketFlags socketFlags)
at Caesura.aSocketTest.<testaSocketRecieveObjectDisposedException>b__6(Socket a) in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\aSocketTest.cs:line 119
at Rhino.Mocks.RhinoMocksExtensions.Expect[T,R](T mock, Function`2 action)
at Rhino.Mocks.RhinoMocksExtensions.Stub[T,R](T mock, Function`2 action)
at Caesura.aSocketTest.testaSocketRecieveObjectDisposedException() in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\aSocketTest.cs:line 119
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="Caesura.aSocketTest.testaSocketRecieveSocketException" executed="True" result="Error" success="False" time="0.001" asserts="0">
                <failure>
                  <message><![CDATA[System.Net.Sockets.SocketException : A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied]]></message>
                  <stack-trace><![CDATA[at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 size, SocketFlags socketFlags)
at Caesura.aSocketTest.<testaSocketRecieveSocketException>b__4(Socket a) in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\aSocketTest.cs:line 108
at Rhino.Mocks.RhinoMocksExtensions.Expect[T,R](T mock, Function`2 action)
at Rhino.Mocks.RhinoMocksExtensions.Stub[T,R](T mock, Function`2 action)
at Caesura.aSocketTest.testaSocketRecieveSocketException() in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\aSocketTest.cs:line 108
]]></stack-trace>
                </failure>
              </test-case>
            </results>
          </test-suite>
          <test-suite type="TestFixture" name="clientAndserverTest" executed="True" result="Success" success="True" time="0.004" asserts="0">
            <results>
              <test-case name="Caesura.clientAndserverTest.generic001Test" executed="True" result="Success" success="True" time="0.003" asserts="1" />
            </results>
          </test-suite>
          <test-suite type="TestFixture" name="serverTest" executed="True" result="Failure" success="False" time="0.041" asserts="0">
            <results>
              <test-case name="Caesura.serverTest.testServerListen" executed="True" result="Failure" success="False" time="0.001" asserts="1">
                <failure>
                  <message><![CDATA[  Expected: same as <Castle.Proxies.iSocketProxy7fd0c3f7dbd6447c86158d91ce189baf>
  But was:  <Castle.Proxies.iSocketProxy7fd0c3f7dbd6447c86158d91ce189baf>
]]></message>
                  <stack-trace><![CDATA[at Caesura.serverTest.testServerListen() in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\serverTest.cs:line 57
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="Caesura.serverTest.testServerNoParameterConstructor" executed="True" result="Success" success="True" time="0.011" asserts="1" />
              <test-case name="Caesura.serverTest.testServerSendString" executed="True" result="Failure" success="False" time="0.001" asserts="1">
                <failure>
                  <message><![CDATA[  Expected: -1
  But was:  4
]]></message>
                  <stack-trace><![CDATA[at Caesura.serverTest.testServerSendString() in c:\Users\Carterj3-Tower\Documents\GitHub\Caesura\Caesura\Caesura\serverTest.cs:line 68
]]></stack-trace>
                </failure>
              </test-case>
              <test-case name="Caesura.serverTest.testServerSetSocket" executed="True" result="Success" success="True" time="0.001" asserts="1" />
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>